<a href="https://colab.research.google.com/github/kit-v4399/229351-StatisticalLearning/blob/main/Copy_of_Lab08_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Statistical Learning for Data Science 2 (229352)
#### Instructor: Donlapark Ponnoprat

#### [Course website](https://donlapark.pages.dev/229352/)

## Lab #8

There are several deep learning frameworks in Python.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/2560px-PyTorch_logo_black.svg.png" width="100"/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg" width="40"/><img src="https://assets-global.website-files.com/621e749a546b7592125f38ed/62277da165ed192adba475fc_JAX.jpg" width="100"/>

In this Lab, we will use PyTorch

In [ ]:
import numpy as np

import torch

# Tensor basics

## Basic tensor creation

### Creating a scalar (1D) tensor

In [ ]:
a = torch.tensor([1.])
a

tensor([1.])

### Convert a tensor to scalar

In [ ]:
b = a[0].item()
b

1.0

### Creating 2D tensor

In [ ]:
c = torch.tensor([[1., 2.], [3., 4.]])
c

tensor([[1., 2.],
        [3., 4.]])

## Tensor and Numpy

### Convert from tensor to numpy array

In [ ]:
d = c.numpy()
d

array([[1., 2.],
       [3., 4.]], dtype=float32)

### Convert from numpy array to tensor

In [ ]:
f = torch.from_numpy(d)
f

tensor([[1., 2.],
        [3., 4.]])

## PyTorch and GPU

check if GPU is available

In [ ]:
torch.cuda.is_available()

True

In [ ]:
c = c.cuda()
c

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')

In [ ]:
e = c.cpu().numpy()
e

array([[1., 2.],
       [3., 4.]], dtype=float32)

## Basic operations

In [ ]:
c * 2

tensor([[2., 4.],
        [6., 8.]], device='cuda:0')

In [ ]:
c - 1

tensor([[0., 1.],
        [2., 3.]], device='cuda:0')

### Matrix multiplication

In [ ]:
A = torch.tensor([[4, 5], [8, 9]])
B = torch.tensor([[1, 4], [7, 8]])

torch.matmul(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
torch.mm(A, B)

tensor([[ 39,  56],
        [ 71, 104]])

In [ ]:
A @ B

tensor([[ 39,  56],
        [ 71, 104]])

### Matrix transpose

In [ ]:
A.t()

tensor([[4, 8],
        [5, 9]])

## Creating a specific type of tensor

In [ ]:
a = torch.zeros(1, 2, 3)
a

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:

b = torch.ones(1, 2, 3)
b

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
I = torch.eye(3)
I

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
R1 = torch.rand(2, 3)
R1

tensor([[0.6503, 0.2428, 0.4226],
        [0.7262, 0.8005, 0.6947]])

In [ ]:
R2 = torch.randn(2, 3)
R2

tensor([[-0.5049,  2.3785, -1.4847],
        [-0.1500, -0.0160, -0.1120]])

In [ ]:
a = torch.arange(6)
a

tensor([0, 1, 2, 3, 4, 5])

## Tensor's shape

In [ ]:
R1.shape

torch.Size([2, 3])

### Checking the shape of a tensor

In [ ]:
u = torch.arange(6)
u.shape

torch.Size([6])

### Changing the shape of a tensor

In [ ]:
v = u.reshape(2, 3)
v.shape

torch.Size([2, 3])

In [ ]:
w = u.view(3, 2)
w

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In general, use `reshape`, but if you are worried about the memory usage, use `view`.

### Stacking and concatenating tensors

In [ ]:
a = torch.arange(4)
b = torch.arange(4) + 1

c = torch.stack([a, b], axis=0)
c

tensor([[0, 1, 2, 3],
        [1, 2, 3, 4]])

In [ ]:
d = torch.stack([a, b], axis=1)
d


tensor([[0, 1],
        [1, 2],
        [2, 3],
        [3, 4]])

In [ ]:
e = torch.cat([a, b], axis=0)
e

tensor([0, 1, 2, 3, 1, 2, 3, 4])

In [ ]:
display(a,b)

tensor([0, 1, 2, 3])

tensor([1, 2, 3, 4])

In [ ]:
f = torch.cat([a.reshape(2, 2), b.reshape(2, 2)], axis=0)
f

tensor([[0, 1],
        [2, 3],
        [1, 2],
        [3, 4]])

### Squeezing a tensor (removing an extra dimension)

In [ ]:
A = torch.zeros(1, 2, 3)
B = A.squeeze()
B

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
C = B.unsqueeze(axis=0)
C

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

### Unsqueezing a tensor (adding an extra dimension)

In [ ]:
# H.shape = (6, )


## Indexing

In [ ]:
P = torch.arange(12).reshape(3,4)
print(P)
print(P[0])
print(P[:, 0])
print(P[-1])
print(P[:, -1])
print(P[-2:])
print(P[:, -2:])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([0, 1, 2, 3])
tensor([0, 4, 8])
tensor([ 8,  9, 10, 11])
tensor([ 3,  7, 11])
tensor([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 2,  3],
        [ 6,  7],
        [10, 11]])


In [ ]:
torch.inverse(torch.tensor([[1., 2.], [3., 4.]]))

tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])

# Exercise

In this exercise, we will simulate data to perform linear regression with 200 rows and 7 variables.

1. Create three random $N(0,1)$ tensors: `X`, `b` and `e` with `X.shape = (200, 7)`, `b.shape = (8, 1)` and `e.shape = (200, 1)` respectively.
2. Create a tensor that contains only 1's with shape `(200, 1)`.
3. Modify tensor `X` by adding the tensor in 2. as the first column.
4. Compute `y` using the following formula:
$$ y = Xb + e $$.
5. Fit a linear regression to the data `X` and `y` and obtain a tensor of estimated coefficient `b_hat`. The formula for `b_hat` is given by:
$$ \hat{b} = (X^TX)^{-1}X^Ty $$
Note: use `torch.inverse(...)` to calculate the inverse
6. Compute the predictions `y_hat`, given by:
$$ \hat{y} = X\hat{b} $$
7. Convert both `y` and `y_hat` from tensor to Numpy array and calculate MSE:
$$ MSE = \frac{1}{200}\sum_{i=1}^{200} (y_i - \hat{y}_i)^2 $$

In [ ]:
X = torch.tensor([[2, 3, 2], [4, 6, 7], [7, 2, 4]])
print(X)

X = torch.tensor([[1, 2, 3, 2], [1, 4, 6, 7], [1, 7, 2, 4]])
print(X)

tensor([[2, 3, 2],
        [4, 6, 7],
        [7, 2, 4]])
tensor([[1, 2, 3, 2],
        [1, 4, 6, 7],
        [1, 7, 2, 4]])


In [ ]:
X = torch.randn(200, 7)
b = torch.randn(8, 1)
e = torch.randn(200, 1)

In [ ]:
one = torch.ones(200, 1)

In [ ]:
X

tensor([[ 0.4901, -0.1704,  0.5641,  ..., -1.6426, -0.7454,  1.8274],
        [ 0.0253,  0.8271,  1.4401,  ..., -0.7092,  1.3471,  0.6070],
        [-0.8967,  0.9164, -0.4996,  ..., -0.4722,  0.6067,  0.1439],
        ...,
        [ 0.6438, -0.3961, -0.2534,  ..., -0.4974,  0.3722, -0.0573],
        [-1.5747,  0.8473,  2.0427,  ..., -0.2930, -2.2564, -1.5477],
        [ 0.7164,  0.6876, -1.5511,  ..., -2.7429,  1.4727, -0.3164]])

In [ ]:
X = torch.cat([one, X], axis=1)
X

tensor([[ 1.0000,  0.4901, -0.1704,  ..., -1.6426, -0.7454,  1.8274],
        [ 1.0000,  0.0253,  0.8271,  ..., -0.7092,  1.3471,  0.6070],
        [ 1.0000, -0.8967,  0.9164,  ..., -0.4722,  0.6067,  0.1439],
        ...,
        [ 1.0000,  0.6438, -0.3961,  ..., -0.4974,  0.3722, -0.0573],
        [ 1.0000, -1.5747,  0.8473,  ..., -0.2930, -2.2564, -1.5477],
        [ 1.0000,  0.7164,  0.6876,  ..., -2.7429,  1.4727, -0.3164]])

In [ ]:
y = X @ b + e
y

tensor([[ 1.1573],
        [ 1.6298],
        [ 3.7838],
        [ 2.2950],
        [ 2.5356],
        [-0.5698],
        [ 1.6849],
        [ 3.2525],
        [-1.3175],
        [-2.3503],
        [-1.7157],
        [-0.4580],
        [ 1.4207],
        [ 3.2462],
        [-2.1137],
        [-1.1759],
        [-0.0942],
        [ 2.0388],
        [-0.4446],
        [-1.0208],
        [ 4.8014],
        [ 5.0695],
        [-0.1027],
        [ 2.7513],
        [ 0.9679],
        [-0.3395],
        [ 1.1440],
        [-2.0066],
        [ 2.5212],
        [-0.5239],
        [-0.5000],
        [ 0.2728],
        [-0.2687],
        [ 0.9757],
        [-1.2079],
        [ 2.7954],
        [ 3.9580],
        [ 0.9507],
        [-1.1225],
        [ 0.8857],
        [ 2.5923],
        [ 2.0061],
        [-2.0683],
        [ 2.4503],
        [ 2.7464],
        [ 1.3443],
        [ 3.7819],
        [ 4.0454],
        [ 1.7653],
        [-3.8490],
        [ 0.2280],
        [ 3.6108],
        [ 2.

In [ ]:
b_hat = torch.inverse(X.t() @ X) @ X.t() @ y
b_hat

tensor([[ 0.5762],
        [ 1.0116],
        [ 1.1327],
        [-0.6571],
        [ 0.6439],
        [-0.3339],
        [ 0.2160],
        [ 0.1422]])

In [ ]:
y_hat = X @ b_hat
y_hat

tensor([[ 1.3188],
        [ 0.7206],
        [ 1.8428],
        [ 1.0173],
        [ 2.7778],
        [-1.2155],
        [ 0.9455],
        [ 1.8003],
        [-0.2141],
        [-2.3152],
        [-0.5208],
        [ 0.0260],
        [ 0.7230],
        [ 3.9765],
        [-1.9763],
        [ 1.0200],
        [-0.8178],
        [ 1.5565],
        [ 0.5252],
        [-2.8736],
        [ 2.5889],
        [ 3.0507],
        [ 0.9892],
        [ 2.0880],
        [ 1.7549],
        [-0.1722],
        [ 2.6126],
        [-1.0254],
        [ 2.3786],
        [ 0.0600],
        [ 0.0400],
        [-0.4879],
        [ 0.5856],
        [ 1.4011],
        [ 0.5828],
        [ 2.4573],
        [ 1.4616],
        [ 0.6540],
        [ 0.1582],
        [ 1.9877],
        [ 2.6764],
        [ 0.9436],
        [-1.8536],
        [ 1.4931],
        [ 1.9833],
        [ 2.9036],
        [ 2.4246],
        [ 3.1436],
        [ 1.9004],
        [-3.5495],
        [ 0.6697],
        [ 2.8412],
        [ 1.

In [ ]:
y = y.numpy()
y_hat = y_hat.numpy()

np.float32(1.0064452)